### ISSUE TITLE
ModuleNotFoundError: No module named 'wsgi'

### ISSUE THREAD

**Issue by TRSWNCA** [ODM2/ODM2DataSharingPortal#544]
I was just following the steps on https://github.com/ODM2/ODM2DataSharingPortal/blob/main/doc/deployment_guide.md
However when I  run `gunicorn wsgi:application --bind 0.0.0.0:8000` I just crashed.

I Founded answer on stackoverflow, but it tells me that I should use like `gunicorn projectname.wsgi` command instead.

Sorry for that, but I'm in a mess. Hope someone could help me.

I'm using Ubuntu20.04LTS X86_64, Here's the log:

```
(ODM2DataSharingPortal) tank@ubuntu:/opt/ODM2DataSharingPortal/src$ gunicorn wsgi:application --bind 0.0.0.0:8000 --preload
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/opt/miniconda3/envs/ODM2DataSharingPortal/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
```

**Comment by TRSWNCA** [comment]
By the way, I am using master branch instead of develop branch.
So I didn't find `conda env create -f /opt/ODM2DataSharingPortal/environment_py38_dj22.yml` this yml file, and use `environment.yml` instead.
Not knowing whether it had effects. :<

**Comment by TRSWNCA** [comment]
Solved by using `gunicorn WebSDL.wsgi:application --bind 0.0.0.0:8000`. XD.
